# Generated by Django 4.0 on 2023-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
